version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - backend

  back:
    build:
      context: ./.
    environment:
      MONGO_URL: mongodb://mongoadmin:secret@mongo:27017/
      MONGO_DB_NAME: dev
      MONGO_AUTH_SOURCE: admin
      JWT_SECRET: 12345
      JWT_EXPIRATION_TIME: 60m
      HASH_ROUNDS: 10
    networks:
      - backend

networks:
  backend:
